import SwiftUI
import shared

/// Main tab navigation view for TrailGlass iOS app
struct MainTabView: View {
    @StateObject private var appComponent: IOSAppComponentWrapper

    init() {
        _appComponent = StateObject(wrappedValue: IOSAppComponentWrapper())
    }

    var body: some View {
        TabView {
            // Timeline tab
            EnhancedTimelineView(controller: appComponent.component.timelineController)
                .tabItem {
                    Label("Timeline", systemImage: "clock.fill")
                }

            // Trips tab
            TripsView(tripsController: appComponent.component.tripsController)
                .tabItem {
                    Label("Trips", systemImage: "figure.walk")
                }

            // Map tab
            MapScreen(mapController: appComponent.component.mapController)
                .tabItem {
                    Label("Map", systemImage: "map.fill")
                }

            // Places tab
            PlacesView(placesController: appComponent.component.placesController)
                .tabItem {
                    Label("Places", systemImage: "mappin.and.ellipse")
                }

            // Stats tab
            EnhancedStatsView(statsController: appComponent.component.statsController)
                .tabItem {
                    Label("Stats", systemImage: "chart.bar.fill")
                }

            // Settings tab
            EnhancedSettingsView(settingsController: appComponent.component.settingsController)
                .tabItem {
                    Label("Settings", systemImage: "gear")
                }
        }
    }
}

/// Wrapper for IOSAppComponent to make it Observable
class IOSAppComponentWrapper: ObservableObject {
    let component: IOSAppComponent

    init() {
        self.component = createIOSAppComponent()
    }
}

/// Create the iOS app component with all dependencies
func createIOSAppComponent() -> IOSAppComponent {
    // This function would be generated by kotlin-inject or created manually
    // For now, return a mock implementation
    // In production, this should create the actual DI component
    fatalError("IOSAppComponent needs to be implemented with proper DI setup")
}

/// Protocol defining the iOS app component interface
protocol IOSAppComponent {
    var timelineController: EnhancedTimelineController { get }
    var tripsController: TripsController { get }
    var mapController: MapController { get }
    var placesController: PlacesController { get }
    var statsController: EnhancedStatsController { get }
    var settingsController: SettingsController { get }
    var syncManager: SyncManager { get }
    var locationTracker: LocationTracker { get }
}

#Preview {
    MainTabView()
}
